### ISSUE TITLE
BakaXL账户系统无法登录（非启动器内）

### ISSUE THREAD

**Issue by XiaoLL0323** [BakaXL-Support/BakaXL-QA-docs#121]
- [] 我已查阅帮助文档，我并没有找到我需要的解决方案
- [] 在issues中和discussions也没有与我遇到的问题相关的讨论

### :grey_question: 发生的问题
BakaXL账户系统网站左下角的“已有账号？“的点击无效（俗称点不动a！！！）

### :eyes: 截图

- 关于该问题的截图 :
![{9B44E408-773C-4916-B90F-E6931A2EEDFC}](https://github.com/BakaXL-Support/BakaXL-QA-docs/assets/108166480/eca5bd09-d111-419f-8cc9-bc8d2c708904)

### :mag_right: 复现步骤

无

### :page_with_curl: 附注

无

没毛病。。。

**Comment by XiaoMouz** [comment]
BakaXL Network 正在迁移至新账户系统
