### ISSUE TITLE
关于账户邮箱和ID

### ISSUE THREAD

**Issue by Eremocene** [BakaXL-Support/BakaXL-QA-docs#130]
- [x] 我确认此功能未在计划项目中
- [] 我确认无类似issue

### 谬误/新增
关于账户邮箱和ID

### 具体描述
我分不清BakaXL账户邮箱和BakaXL Network ID的区别，因为ID可以从联机大厅看到，但是账户邮箱还不知道。而爱发电需要提供账户邮箱。

### 附加信息
是否需要在帮助文档里添加如何查看账户邮箱的说明，或者阐述ID和账户邮箱的区别。

**Comment by XiaoMouz** [comment]
邮箱用于确认身份，id也能，由于用户名后有独一无二的id编号，因此能确保账户名+编号的唯一性

如果tt没犯懒癌你可以提供id给他，也能验证身份
或者你可以在邮箱app内搜索带bakaxl关键字的邮件

关于文档，目前在预热 4.0 版本的帮助文档，届时会有更详细的说明，BakaXL 账户系统的完善依赖于账户系统，你可以前往 https://account.baka.zone/ 查看

> 由于开学季导致 issue 回复慢感到非常抱歉
