### ISSUE TITLE
关于 IPv6 防火墙

### ISSUE THREAD

**Issue by bwtx2022** [BakaXL-Support/BakaXL-QA-docs#34]
- [x] 我确认此功能未在计划项目中
- [x] 我确认无类似issue

### 谬误/新增
提示用户关闭IPv6防火墙

### 具体描述

¯\_(ツ)_/¯

### 附加信息

¯\_(ツ)_/¯

**Comment by XiaoMouz** [comment]
我不道啊

**Comment by XiaoMouz** [comment]
好了，我选择让用户找ISP
