### ISSUE TITLE
将 Minecraft 1.8 - 1.16.5 中的部分内容转移到其他文档

### ISSUE THREAD

**Issue by Seayay** [BakaXL-Support/BakaXL-QA-docs#51]
- [x] 我确认此功能未在计划项目中
- [x] 我确认无类似issue

### 谬误/新增
此文档中部分内容同样适用于其他版本，建议新增文档。

### 具体描述
将除 Forge 崩溃如何处理 之外的所有内容新增文档。

### 附加信息
没有。

**Comment by XiaoMouz** [comment]
迁移到哪

**Comment by Seayay** [comment]
整个新文档
