### ISSUE TITLE
添加BakaXL错误代码对应的注释

### ISSUE THREAD

**Issue by Souiken** [BakaXL-Support/BakaXL-QA-docs#67]
- [x] 我确认此功能未在计划项目中
- [x] 我确认无类似issue

### 谬误/新增

BakaXL错误代码及注释

### 具体描述

添加关于BakaXL错误代码及注释的页面

### 附加信息

无

**Comment by bwtx2022** [comment]
@TT702 这个能提供一下吗

**Comment by XiaoMouz** [comment]
不打算对 3.0 版本的 BakaXL 错误代码进行注解
目前的错误代码大部分情况下都只是对 C# 报错进行处理并生成统一日志供开发者使用，用户端大部分情况下无法解决问题或无需解决相关问题
