### ISSUE TITLE
添加 通过mod文件夹添加mod

### ISSUE THREAD

**Issue by Souiken** [BakaXL-Support/BakaXL-QA-docs#85]
- [x] 我确认此功能未在计划项目中
- [x] 我确认无类似issue

### 谬误/新增

添加如何往mod文件夹内添加mod和添加如何在高级核心内管理mod。

### 具体描述

无

### 附加信息

无

**Comment by bwtx2022** [comment]
@XiaoMouz 这个要不来写写？ 我没空了（

**Comment by XiaoMouz** [comment]
> @XiaoMouz 这个要不来写写？ 我没空了（

Mod 不急，最近我有其它事（

**Comment by bwtx2022** [comment]
这个没人写的话我来写罢
